# -----------------------------
# GPUSStack Full Metrics Definition
# All metrics include full hierarchy labels
# -----------------------------
gpustack_metrics:
  seabed:num_requests_running:
    type: Gauge
    description: "Number of requests currently being processed."

  seabed:num_requests_waiting:
    type: Gauge
    description: "Number of requests waiting in the queue."

  seabed:num_requests_swapped:
    type: Gauge
    description: "Number of requests swapped out to CPU."

  seabed:prefix_cache_hit_rate:
    type: Gauge
    description: "Prefix cache hit rate"

  seabed:kv_cache_usage_ratio:
    type: Gauge
    description: "KV-cache usage ratio. 1.0 means fully used (100%)."

  seabed:prefix_cache_queries:
    type: Counter
    description: "Number of prefix cache queries, measured by the total queried tokens."

  seabed:prefix_cache_hits:
    type: Counter
    description: "Number of prefix cache hits, measured by the total hit tokens."

  seabed:prompt_tokens:
    type: Counter
    description: "Total number of prefill tokens processed."

  seabed:generation_tokens:
    type: Counter
    description: "Total number of generated tokens."

  seabed:request_prompt_tokens:
    type: Histogram
    description: "Number of prefill tokens processed."

  seabed:request_generation_tokens:
    type: Histogram
    description: "Number of generation tokens processed."

  seabed:time_to_first_token_seconds:
    type: Histogram
    description: "Time to generate first token."

  seabed:time_per_output_token_seconds:
    type: Histogram
    description: "Average time spent to produce each output token."

  seabed:e2e_request_latency_seconds:
    type: Histogram
    description: "End-to-end request latency."

  seabed:request_success:
    type: Counter
    description: "Total number of successful requests."

  seabed:inter_token_latency_seconds:
    type: Histogram
    description: "Time to generate the next token after the previous token has been produced."


# -----------------------------
# Runtime Metrics Mapping (user-configurable)
# -----------------------------
runtime_mapping:
  vLLM:
    "*": # 0.11.0
      vllm:num_requests_running: seabed:num_requests_running
      vllm:num_requests_waiting: seabed:num_requests_waiting
      vllm:num_requests_swapped: seabed:num_requests_swapped
      vllm:prefix_cache_hits: seabed:prefix_cache_hits
      vllm:prefix_cache_queries: seabed:prefix_cache_queries
      vllm:kv_cache_usage_perc: seabed:kv_cache_usage_ratio
      vllm:prompt_tokens: seabed:prompt_tokens
      vllm:generation_tokens: seabed:generation_tokens
      vllm:time_to_first_token_seconds: seabed:time_to_first_token_seconds
      vllm:request_time_per_output_token_seconds: seabed:time_per_output_token_seconds
      vllm:e2e_request_latency_seconds: seabed:e2e_request_latency_seconds
      vllm:request_success: seabed:request_success
      vllm:request_prompt_tokens: seabed:request_prompt_tokens
      vllm:request_generation_tokens: seabed:request_generation_tokens
      vllm:inter_token_latency_seconds: seabed:inter_token_latency_seconds
    "<0.11.0":
      vllm:time_per_output_token_seconds: seabed:time_per_output_token_seconds
    "<0.9.2":
       vllm:gpu_prefix_cache_hits: seabed:prefix_cache_hits
       vllm:gpu_prefix_cache_queries: seabed:prefix_cache_queries
       vllm:gpu_cache_usage_perc: seabed:kv_cache_usage_ratio

  SGLang:
    "*": # 0.5.4
      sglang:num_running_reqs: seabed:num_requests_running
      sglang:num_queue_reqs: seabed:num_requests_waiting
      sglang:cached_tokens_total: seabed:prefix_cache_hits
      sglang:cache_hit_rate: seabed:prefix_cache_hit_rate
      sglang:token_usage: seabed:kv_cache_usage_ratio
      sglang:prompt_tokens: seabed:prompt_tokens
      sglang:generation_tokens: seabed:generation_tokens
      sglang:time_to_first_token_seconds: seabed:time_to_first_token_seconds
      sglang:e2e_request_latency_seconds: seabed:e2e_request_latency_seconds
      sglang:inter_token_latency_seconds: seabed:inter_token_latency_seconds
    "<=0.4.4":
      sglang:time_per_output_token_seconds: seabed:time_per_output_token_seconds
      
  MindIE:
    "*": # 2.1.RC2
      num_requests_running: seabed:num_requests_running
      num_requests_waiting: seabed:num_requests_waiting
      num_requests_swapped: seabed:num_requests_swapped
      npu_prefix_cache_hit_rate: seabed:prefix_cache_hit_rate
      npu_cache_usage_perc: seabed:kv_cache_usage_ratio
      prompt_tokens: seabed:prompt_tokens
      generation_tokens: seabed:generation_tokens
      time_to_first_token_seconds: seabed:time_to_first_token_seconds
      time_per_output_token_seconds: seabed:time_per_output_token_seconds
      e2e_request_latency_seconds: seabed:e2e_request_latency_seconds
      request_success: seabed:request_success
      request_prompt_tokens: seabed:request_prompt_tokens
      request_generation_tokens: seabed:request_generation_tokens
